-- UNO TEA QR ORDER — Supabase setup
-- Run this whole file in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  image_url text,
  description text,
  is_available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  table_number text not null,
  status text not null default 'Mới' check (status in ('Mới','Đang làm','Hoàn thành')),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_name text not null,
  price integer not null check (price >= 0),
  quantity integer not null check (quantity > 0)
);

alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Public customers: only see available menu.
drop policy if exists "menu public read" on public.menu_items;
create policy "menu public read" on public.menu_items for select using (is_available = true or auth.role() = 'authenticated');

-- Customers can create orders/items. Staff can manage them after login.
drop policy if exists "orders public insert" on public.orders;
create policy "orders public insert" on public.orders for insert with check (true);
drop policy if exists "order items public insert" on public.order_items;
create policy "order items public insert" on public.order_items for insert with check (true);

drop policy if exists "orders staff select" on public.orders;
create policy "orders staff select" on public.orders for select to authenticated using (true);
drop policy if exists "orders staff update" on public.orders;
create policy "orders staff update" on public.orders for update to authenticated using (true) with check (true);
drop policy if exists "orders staff delete" on public.orders;
create policy "orders staff delete" on public.orders for delete to authenticated using (true);

drop policy if exists "order items staff select" on public.order_items;
create policy "order items staff select" on public.order_items for select to authenticated using (true);

drop policy if exists "menu staff insert" on public.menu_items;
create policy "menu staff insert" on public.menu_items for insert to authenticated with check (true);
drop policy if exists "menu staff update" on public.menu_items;
create policy "menu staff update" on public.menu_items for update to authenticated using (true) with check (true);
drop policy if exists "menu staff delete" on public.menu_items;
create policy "menu staff delete" on public.menu_items for delete to authenticated using (true);

-- Realtime for order updates.
do $$ begin
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then null;
end $$;

-- Starter menu. Replace/add your real menu in Admin.
insert into public.menu_items (name,category,price,image_url,description,sort_order)
select * from (values
('Trà sữa UNO','Trà sữa',35000,'logo.jpg','Trà sữa thơm béo, vị đặc trưng UNO.',1),
('Trà đào cam sả','Trà trái cây',32000,'logo.jpg','Thanh mát, thơm đào và cam.',2),
('Trà vải','Trà trái cây',32000,'logo.jpg','Vị vải dịu, dễ uống.',3),
('Matcha latte','Matcha',39000,'logo.jpg','Matcha đậm vị, sữa mịn.',4),
('Cà phê sữa','Cà phê',30000,'logo.jpg','Cà phê rang thơm.',5)
) as v(name,category,price,image_url,description,sort_order)
where not exists (select 1 from public.menu_items);
